######################################################################
# Automatically generated by qmake (2.01a) ?? ?? 22 15:16:15 2012
######################################################################

# 全局变量
include (../../dev.pri)

TEMPLATE    = app
TARGET      = SerialportServer
DEFINES     += QT_NO_STL_WCHAR UNICODE _UNICODE
INCLUDEPATH	= . \
		$$INCLUDE_PATH \
		../esframework

DESTDIR     = $$BIN_PATH
OBJECTS_DIR = $$BUILD_PATH/$$TARGET
MOC_DIR     = $$OBJECTS_DIR
RCC_DIR     = $$OBJECTS_DIR
UI_DIR      = $$OBJECTS_DIR

LIBS        += -L$$LIB_PATH
LIBS        += -l$$qtLibraryTarget(esframework)

QT          += xml serialport widgets core
CONFIG	    += console


win32 {
   target.path=../../../install/bin
   INSTALLS += target
   QMAKE_CXXFLAGS_DEBUG += /Od
}

# Input
HEADERS += SerialportServer.pro \
	*.h 
SOURCES += *.cpp

TARGET = $$qtLibraryTarget($$TARGET)
