######################################################################
# Automatically generated by qmake (2.01a) ?? ?? 8 16:02:21 2015
######################################################################

TEMPLATE = app
DEFINES     += QT_NO_STL_WCHAR UNICODE _UNICODE
INCLUDEPATH	= .
TARGET = $$qtLibraryTarget(xmlbinding)
DESTDIR = ../../../bin
CONFIG   += console
CONFIG   -= app_bundle

DEPENDPATH += .

INCLUDEPATH += . \
	../esframework

QT	+= core xml
QT	-= gui

LIBS += -L../../lib
LIBS += -l$$qtLibraryTarget(esframework)

# Input
HEADERS += xmlbinding.pro  \
	*.h 
SOURCES += *.cpp

